# Generated by Django 4.2.7 on 2023-12-03 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='attraction_en',
            field=models.CharField(max_length=50, null=True, verbose_name='Достопримечательность'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='attraction_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Достопримечательность'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='attraction_type_en',
            field=models.CharField(choices=[('statue', 'Статуя'), ('history_place', 'Историческое место'), ('natural_beauty', 'Природная красота'), ('entertainment_complexes', 'Развлекательный комплекс'), ('religious_place', 'Религиозная место'), ('technical_advances', 'Технические достижения')], max_length=50, null=True, verbose_name='Тип достопримечательности'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='attraction_type_ru',
            field=models.CharField(choices=[('statue', 'Статуя'), ('history_place', 'Историческое место'), ('natural_beauty', 'Природная красота'), ('entertainment_complexes', 'Развлекательный комплекс'), ('religious_place', 'Религиозная место'), ('technical_advances', 'Технические достижения')], max_length=50, null=True, verbose_name='Тип достопримечательности'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='information_en',
            field=models.TextField(null=True, verbose_name='Информация'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='information_ru',
            field=models.TextField(null=True, verbose_name='Информация'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='region_en',
            field=models.CharField(choices=[('osh', 'Ош'), ('batken', 'Баткен'), ('narun', 'Нарын'), ('ussuk-kol', 'Ыссык-Кол'), ('jalal-abad', 'Жалал-Абад'), ('chui', 'Чуй'), ('talas', 'Талас'), ('bishkek', 'Бишкек')], max_length=50, null=True, verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='attraction',
            name='region_ru',
            field=models.CharField(choices=[('osh', 'Ош'), ('batken', 'Баткен'), ('narun', 'Нарын'), ('ussuk-kol', 'Ыссык-Кол'), ('jalal-abad', 'Жалал-Абад'), ('chui', 'Чуй'), ('talas', 'Талас'), ('bishkek', 'Бишкек')], max_length=50, null=True, verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='comment',
            name='attraction_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.attraction'),
        ),
        migrations.AddField(
            model_name='comment',
            name='attraction_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.attraction'),
        ),
        migrations.AddField(
            model_name='comment',
            name='message_en',
            field=models.TextField(max_length=500, null=True, verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='comment',
            name='message_ru',
            field=models.TextField(max_length=500, null=True, verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='comment',
            name='subject_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Тема'),
        ),
        migrations.AddField(
            model_name='comment',
            name='subject_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(max_length=50, verbose_name='Пользователь'),
        ),
    ]
